services:
  - type: web
    name: civicreporter-db
    runtime: python3
    rootDir: backend
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app -w 2 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    healthCheckPath: /healthz
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: MONGODB_URL
        value: mongodb+srv://srivelansv2006_db_user:9YxxIF6TGmNQEsNg@civic-welfare-cluster.rts6zvy.mongodb.net/?retryWrites=true&w=majority&appName=civic-welfare-cluster
      - key: DATABASE_NAME
        value: civic_welfare
      - key: SECRET_KEY
        value: civic-welfare-super-secret-jwt-key-2025-production
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: HOST
        value: 0.0.0.0
      - key: RELOAD
        value: false
      - key: MAX_FILE_SIZE
        value: 10485760
      - key: UPLOAD_DIRECTORY
        value: ./uploads